### ISSUE TITLE
User should be taken somewhere useful after selecting Forgot Password

### ISSUE THREAD

**Issue by LexCaputo** [synapsestudios/oidc-platform#104]
## DESCRIPTION
Once a user clicks Forgot Password and types in their email they are left at a dead end. 

![forgot password](https://user-images.githubusercontent.com/29713167/28278858-6c1de4e2-6ad3-11e7-988f-f4e10d393e3e.PNG)

**Comment by spruce-bruce** [comment]
Somebody has to decide where they should go. There isn't anywhere obviously 'useful' to send them.

**Comment by bobeagan** [comment]
Maybe solved by just a better styled/messaged page that they end up on.  Perhaps still have a link to the login page

**Comment by bobeagan** [comment]
![image](https://user-images.githubusercontent.com/100226/37420456-0c29776e-2774-11e8-9197-ade7ddcf54fe.png)

**Comment by spruce-bruce** [comment]
I'm good with ^
