### ISSUE TITLE
Sending out re-invites doesn't invalidate old invitation links. 

### ISSUE THREAD

**Issue by DemarcatedTitle** [synapsestudios/oidc-platform#105]
## STEPS TO REPRODUCE

1. Send out an invitation email to a valid email address
1. Send out a re-invitation email to the same email address
1. Use the invitation email to set up a password
1. Use the re-invitation email to set up a different password
1. Observe that the password you used in the re-invitation set up is the accounts new password.

**Comment by spruce-bruce** [comment]
This isn't a bug it's just not a thing we cared about. I don't know why we care about this still, but whatever.
