### ISSUE TITLE
Two Forgot Password links on Log In form is redundant 

### ISSUE THREAD

**Issue by dmmcinty** [synapsestudios/oidc-platform#106]
### DESCRIPTION
On the login form, there are two links to the Forgot Password form. Only one is required. 

![screen shot 2017-07-17 at 9 45 47 am](https://user-images.githubusercontent.com/1359068/28279962-0d1373a0-6ad7-11e7-912c-f844d77dcaf6.png)

**Comment by DemarcatedTitle** [comment]
Issue no longer present.
