### ISSUE TITLE
v2.1.0 "verify change email" endpoint crashes with SES driver and default template

### ISSUE THREAD

**Issue by chrisshiplet** [synapsestudios/oidc-platform#209]
`sendChangeEmailVerifyEmail` in v2.1.0 should set a default `subject` in the email's view context so that the default value of `null` won't cause a 500 error from the SES driver.

**Comment by chrisshiplet** [comment]
I'm also not sure my custom templates are respecting the "layout_id" for the email change alerts.

**Comment by spruce-bruce** [comment]
Any resolution on the layout_id thing? If that's still a problem can you file another bug?
