### ISSUE TITLE
Investigate node-oidc-provider updates

### ISSUE THREAD

**Issue by chrisshiplet** [synapsestudios/oidc-platform#297]
Looks like we might be fairly out of date with this library, we should check out the changelog and implement any necessary updates

**Comment by bobeagan** [comment]
Will use this research to determine if this can be done on 2.3.0 or 3.0.0 release

**Comment by spruce-bruce** [comment]
Oh jeez
I wrote that and only really tested that the id_token was right. We haven't been using the password grant yet (and we're the only people who use this) so that's just been sitting there waiting for you to come and notice.

Thanks for pointing that out!

**Comment by spruce-bruce** [comment]
We have a couple major updates to get through and should do it soon. When we do code that I wrote here https://github.com/synapsestudios/oidc-platform/pull/332 can be trimmed down (we won't need a custom setProviderSession function. provider.setProviderSession will return the session)
