### ISSUE TITLE
Allow overriding the subject on the invitation email

### ISSUE THREAD

**Issue by agerbens** [synapsestudios/oidc-platform#317]
We should be able to override the subject on the invitation email when either:

- Using the `invite-email` template
OR
- Passing a template in through the request body.

**Comment by spruce-bruce** [comment]
This might be doable now - or at least I imagined doing this with the `options` column in the template table. The idea being that you can set the subject in the table with `{ subject: 'some subject' }`. Updating the invite endpoint to take a subject seems pretty reasonable to handle dynamic subjects, too
