### ISSUE TITLE
Back Button Behavior

### ISSUE THREAD

**Issue by samrocksc** [synapsestudios/oidc-platform#344]
## Expected Behavior
When logging in, and immediately logging out, clicking the back button to the already used OIDC login page, login is successful

## Current Behavior
When logging in, and immediately logging out, clicking the back button to the already used OIDC login page, login is unsuccessful with error 504.  Attempting to refresh this page produces error 500.

## Possible solutions
- Passing a reroute on back button to refresh page with new idToken

**Comment by samrocksc** [comment]
Referenced issue

**Comment by spruce-bruce** [comment]
Because of the way the node-oidc-proivdier library works I think accomplishing this will be a bit tricky.

**Comment by spruce-bruce** [comment]
Closed because this is just how browsers work.
