### ISSUE TITLE
Update keep-alive duration

### ISSUE THREAD

**Issue by averhulst** [synapsestudios/oidc-platform#471]
Node has a default connection keep-alive setting of 5 seconds and AWS ELB has a default setting to expect those connections to remain open for 60 seconds which causes intermittent 502s between ELB and OIDC. This issue is to update OIDC to keep connections open for slightly longer than the default ELB setting of 60 seconds.

https://adamcrowder.net/posts/node-express-api-and-aws-alb-502/

**Comment by bobeagan** [comment]
Can this be made configable so that on projects where we customize the default ELB timeout, we can make it easy to align the node timeout as well?
