### ISSUE TITLE
SendGrid-related console warning when not using SendGrid

### ISSUE THREAD

**Issue by agerbens** [synapsestudios/oidc-platform#473]
If there's no `SENDGRID_API_KEY` set in the environment, there's a console warning when starting up the API: `API key does not start with "SG.".`

In the sendgrid driver, we probably shouldn't be calling `sgMail.setApiKey(process.env.SENDGRID_API_KEY);` unless the `OIDC_EMAIL_DRIVER` is set to `sendgrid`

Related to https://github.com/synapsestudios/oidc-platform/issues/454

**Comment by spruce-bruce** [comment]
Indeed
