### ISSUE TITLE
Redis connection hangs with AWS Elasticache Redis with TransmitEncryptionEnabled

### ISSUE THREAD

**Issue by agerbens** [synapsestudios/oidc-platform#495]
When using a redis adapter with AWS Elasticache Redis that has `TransmitEncryptionEnabled`, the connection seems to just hang. 

Relevant issue in ioredis:
https://github.com/luin/ioredis/issues/894

I made the fix they mention in that thread here: https://github.com/synapsestudios/oidc-platform/commit/aaffb8b4b7cbb0450b4841a0dfb5faede000e1af and tested it with a new redis instance with Encryption in-transit and Encryption at-rest enabled and it seems to have worked.

**Comment by spruce-bruce** [comment]
Nice!

**Comment by agerbens** [comment]
This wasn't a bug, and the code change has been reverted. Sorry for the trouble.
