### ISSUE TITLE
Add allowUserRegistration configurable by env var

### ISSUE THREAD

**Issue by pcavagna** [synapsestudios/oidc-platform#67]
## DESCRIPTION
Provide a configuration variable to allow the enabling/disabling of user registration. If registration is off then users can only be added if they're invited by a client app. If user registration is on then the registration url should be enabled and available from the login screen (or linkable by the client app)

**Comment by spruce-bruce** [comment]
We need to figure out how we're going to configure clients to allow registration and then once that's done we can decide when/how to show a registration link. 

Until then user registration is only semi-supported.

**Comment by spruce-bruce** [comment]
Updated name/description of this issue to be a more robust feature and allows us to tighten up our registration behavior.
