### ISSUE TITLE
draftjs-editor: stylesheet rethink/cleanup

### ISSUE THREAD

**Issue by pcavagna** [synapsestudios/oidc-platform#69]
## DESCRIPTION

We should split stylesheets into:

Typography/content-area related styles
DraftJS Input + Controls styles

This will allow projects with admin interfaces to use both, while projects with read-only editor displays will not have the gray box / control styling.

Want to give this a little more thought, but this would be a minimum solution based on the current implementation's pain-points.

**Comment by bobeagan** [comment]
Wrong repo
