### ISSUE TITLE
Throw warning when missing Mailgun domain env var

### ISSUE THREAD

**Issue by chrisshiplet** [synapsestudios/oidc-platform#80]
Silent failures make me sad

**Comment by bobeagan** [comment]
Probably still a failure when it is SES instead of mailgun, more information needed: when does it throw the error, what is the error.

This issue description makes me sad.

**Comment by chrisshiplet** [comment]
Mail sending fails silently when you forget to plug in the Mailgun environment variable ¯\_(ツ)_/¯
